spring:
  profiles:
    active: dev


#server:
#  port: 8082
#  servlet:
#    context-path: /luckymoney
#
## limit视为一个对象进行配置
#limit:
#  minMoney: 1
#  maxMoney: 9999
#  description: 最少要发${limit.minMoney}元，最多发${limit.maxMoney}元